#!/bin/bash


_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $MORPHO_REPO == "MorphoBot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0JJSEFSSUJBQlVIVS9CSUhBUklfVVNFUkJPVC9hcmNoaXZlL21haW4uemlw" | base64 -d
    elif [[ $MORPHO_REPO == "Morphobot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0JJSEFSSUJBQlVIVS9CSUhBUklfVVNFUkJPVC9hcmNoaXZlL21haW4uemlw" | base64 -d
    elif [[ $MORPHO_REPO =~ $regex ]]
    then
        if [[ $MORPHO_REPO ]]
        then
            echo "${MORPHO_REPO}/archive/${MORPHO_REPO_BRANCH}.zip"
        else
            echo "${MORPHO_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0JJSEFSSUJBQlVIVS9CSUhBUklfVVNFUkJPVC9hcmNoaXZlL21haW4uemlw" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="mymorphobot.zip"
    echo "  Downloading source code ..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    MORPHOPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd $MORPHOPATH
    echo "  • Starting MorphoBot •  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m morphobot
}

start_bot
